import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { TetrislyProvider } from '@virtuslab/tetrisly-react';

const inter = Inter({ subsets: ["latin"], weight: ["400", "500", "600"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;450;600&display=swap" rel="stylesheet" />
        </head>
      <body className={inter.className}>
        <TetrislyProvider>{children}</TetrislyProvider>
      </body>
    </html>
  );
}
